version: '3'

services:
  frontend:
    build: './frontend'
    restart: always
    ports:
      - "80:80"
    depends_on:
      - 'backend'
  backend:
    build: './backend'
    restart: always
    command: 'python main.py runserver'
    depends_on:
      - 'postgres'
  postgres:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql:/var/lib/postgresql
volumes:
  postgresql:
    driver: local