version: '3'

services:
  frontend:
    build: './frontend'
    restart: always
    ports:
      - "80:80"
    depends_on:
      - 'backend'
  backend:
    build: './backend'
    restart: always
    command: 'python main.py runserver'
    depends_on:
      - 'postgres'
  postgres:
    restart: always
    image: postgres:10.4
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
    volumes:
      - postgresql:/var/lib/postgresql
volumes:
  postgresql:
    driver: local